services:
  backend:
    build: ./backend
    ports:
      - "8080:8081"
    volumes:
      - backend-data:/app
    environment:
      CGO_ENABLED: "0"
      GOOS: "linux"
    restart: always
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  backend-data: