services:
  backend:
    build: ./backend
    ports:
      - "8080:8081"
    volumes:
      - backend-data:/app
    environment:
      - CGO_ENABLED=${CGO_ENABLED:-0}
      - GOOS=${GOOS:-linux}
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - app-network
    healthcheck:
      test: CMD curl --fail http://localhost:8081/health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s


networks:
  app-network:
    driver: bridge

volumes:
  backend-data: